In [1]:
import random
import numpy as np

In [229]:
person = input('Enter your name: ')
print('Hello', person)

You have chosen:
1 2
Hello (1, 2, 1, 1)


In [247]:
a = raw_input()
print(a)

NameError: name 'raw_input' is not defined

In [2]:
def WonQ(T):
    print("Game Over")

def WonD(T):
    print("WonTalk: Diag Check")

def WonC(T):
    print("WonTalk: Col Check")
    
def WonR(T):
    print("WonTalk: Row Check")


In [3]:
def check(A,B):
    x = 1
    if A < 1:
        print ("Wrong Input, Try Again")
        x = 0
        return x
    if B < 1:
        print ("Wrong Input, Try Again")
        x = 0
        return x
    return x

In [4]:
def CheckRows(T):
    T = T
    print("RowTalk: Computer is checking the rows. The value of T is:", T)
    for i in range(3):
        #print("the value of  i in Row Check is:", i)
        x = 0 # To check whether the computer is winning
        y = 0 # To check whether the user is winning
        for j in range (3):
            #print("the value of j in Row Check is:", j)
            #print("the value of Row A[i,j] is:", A[i,j])
            if A[i,j] == 1:
                x = x + 1
            if A[i,j] == 0:
                y = y + 1
               # print ("RowTalk: CHecking the row", i, j , y)
        #print ("Following is the value of x and y in row check")
        #print (x,y)
        if x == 2 and y == 0 and T==1:
            print("RowTalk: This is my turn and I am going to win")
            T = 2 
            return T # CHANGE
        if x == 0 and y == 2 and T==0:
            print("RowTalk: Yor turn it is now. Call input function")
            T = 2
            return T # NO
        if x == 0 and y == 2 and T== 1:
            print("RowTalk: It is my turn and you are getting a row and I need to block you")
            for j in range (3):
                if A[i,j] > 1:
                    A[i,j] = 1
                    T = 0 #This means user is going to play next
                    return T # CHANGE
        if x == 3:
            print ("RowTalk: Computer wins")
            T == 2
            return T # CHANGE
        if y == 3:
            print ("RowTalk: You Win")
            T == 2
            return T # CHANGE
    print ("RowTalk: I am in check row function and Nothing Happened")
    T =  CheckColumns(T)
    return T

In [5]:
def CheckColumns(T):
    T = T
    print("ColTalk: Computer is  checking the columns")
    for j in range(3):
        # print("the value of j is:", j)
        x = 0 # To check whether the computer is winning
        y = 0 # To check whether the user is winning
        for i in range (3):
            # print("the value of i is:", i)
            if A[i,j] == 1:
                x = x + 1
            if A[i,j] == 0:
                y = y + 1
        #print ("Following is the value of x and y and T", x,y,T)
        if x == 2 and y == 0 and T==1:
            print("ColTalk:This is my turn and I am going to win")
            T = 2
            return T # CHANGE
        if x == 0 and y == 2 and T==0:
            print("ColTalk:Yor turn it is now")
            # T remains same
            T = 0
            return T # NO 
        if x == 0 and y == 2 and T== 1:
            # T changes here
            print("ColTalk:It is my turn and you are getting a column and I need to block you. The computer is going to change the value")
            print("ColTalk:THI IS THE PLACE.THE VALUE OF J IS:",j)
            for i in range (3):
                if A[i,j] != 0:
                    A[i,j] = 1
                    T = 0
                    print("ColTalk:I just prevented a row death.Now it is your turn")
                    return T #Change
        if x == 3:
            # T changes
            print ("ColTalk:Game over!!!Computer wins")
            T = 2
            return T
        if y == 3:
            # T changes
            print ("ColTalk:Game over!!!You Win")
            T = 2
            return T #Change
    T = LRCheckDiagonals(T)
    return T

In [6]:
def LRCheckDiagonals(T):
    T = T
    x = 0 # To check whether the computer is winning
    y = 0 # To check whether the user is winning
    print("LRDiagTalk: Computer is  checking the NW to SE diagonals")
    if A[0,0] == 1:
        x = x + 1
    if A[1,1] == 1:
        x = x + 1
    if A[2,2] == 1:
        x = x + 1
    if A[0,0] == 0:
        y = y + 1
    if A[1,1] == 0:
        y = y + 1
    if A[2,2] == 0:
        y = y + 1
    if x == 0 and y == 2 and T== 1:
        print("LRDiagTalk: It is my turn and you are getting a column and I need to block you")
        for i in range (3):
            if A[i,i] != 0:
                A[i,i] = 1
                T = 0
                return T # Change
    if x == 3:
        print ("LRDiagTalk: Game over!!!Computer wins")
        T = 3
        return T # CHANGE
    if y == 3:
        print ("LRDiagTalk: Game over!!!You Win")
        T = 3
        return T # CHANGE
    T = RLCheckDiagonals(T)
    return T

def RLCheckDiagonals(T):
    x = 0 # To check whether the computer is winning
    y = 0 # To check whether the user is winning
    print("RLDiagTalk: Computer is  checking the SW to NE diagonals")
    if A[0,2] == 1:
        x = x + 1
    if A[1,1] == 1:
        x = x + 1
    if A[2,0] == 1:
        x = x + 1
    if A[0,2] == 0:
        y = y + 1
    if A[1,1] == 0:
        y = y + 1
    if A[2,0] == 0:
        y = y + 1
    if x == 3:
        print ("RLDiagTalk: Game over!!!Computer wins")
        T = 2
        return T # change
    if y == 3:
        print ("RLDiagTalk: Game over!!!You Win")
        T = 2
        return T # CHANGE
    return T


In [7]:
A =  (np.matrix([[11,12,13],[21,22,23],[31,32,33]]))
T = 0 # You start
Turns = 0
UsrTrns = 0
CmpTrns = 0

In [11]:
def input(A):
    R = 1
    C = 3
    T = 1 # This means it is computer 's turn now  
    #Turns = Turns + 1
    print ('You have chosen:')
    #print (A + "," + B)
    print(R,C)
    return R, C, T, Turns

In [12]:
if T == 0:   # T = 0 means user's turn
    (R,C, T, Turns) = input(2)
    R = R - 1
    C = C - 1
    if A[R,C] == 0 or A[R,C] == 1:
        print ("You have chosen a wrong input. Please try again")
        T = 0 # You have to repeat your turn 
        print(A)
        print("Computer is 1, User is 0")
        
    else:
        print(" You have chosen correct input.")
        A [R,C] = 0 # The user's tic tac value is 0 while that of computer 's is 1
        Turns = Turns + 1
        T = 1
        print(A)
        print("It is computer's turn to play now. The Tic-Tac-Toe is as shown above")
        print("Turns is:", Turns)
else:
    print(T)
    print("It is computer's turn now")


       
   
    

You have chosen:
1 3
 You have chosen correct input.
[[11  0  0]
 [21  1 23]
 [31 32 33]]
It is computer's turn to play now. The Tic-Tac-Toe is as shown above
Turns is: 2


In [393]:
T

1

In [13]:
print ("MainProgramTalk:  Computer's value is 1. Your value is 0")
print("MainProgramTalk: the value of turns is:", Turns)
print("MainProgramTalk: the value of T is:", T)
if A[1,1] > 1 and T == 1:
    A[1,1] = 1
    T = 0
    print("Computer has chnaged the central value. The matrix now is:")
    print(A)
    print("It is your turn now. Go and change the value in input function and call it")
if A[1,1] < 2:
    T1 = T
    T = CheckRows(T)
    print("The value of T is")
    print(T)
    print(T1)
    if T == 0:
        print(A)
        print("user please play")
    if T == 1:
        if Turns > 2:
            print("computer has to play by performing second level check")
        if Turns < 3:
            print("computer has to pick a random corner of what is available")
            print(A)
            if A[0,0] > 1:
                A[0,0] = 1
                T = 0
                print(A)
                print("user to play now")

MainProgramTalk:  Computer's value is 1. Your value is 0
MainProgramTalk: the value of turns is: 2
MainProgramTalk: the value of T is: 1
RowTalk: Computer is checking the rows. The value of T is: 1
RowTalk: It is my turn and you are getting a row and I need to block you
The value of T is
0
1
[[ 1  0  0]
 [21  1 23]
 [31 32 33]]
user please play


In [411]:
def seccheck(T):
    if A[1,1] == 1:
        if A[0,2] == 0 and A[2,0] == 1:
            if A[0,0] > 1:
                A[0,0] = 1
                T = 0
                return T
            else:
                if A[2,2] > 1:
                    A[2,2] = 1
                    T = 0
                    return T
        if A[2,2] == 0 and A[0,0] == 1:
            if A[2,0] > 1:
                A[2,0] = 1
                T = 0
                return T
            else:
                if A[2,2] > 1:
                    A[2,2] = 1
                    T = 0
                    return T
    
        

In [161]:
R

1

 You have chosen correct input and your input is
 Computer's value is 0. Your value is 1


22

0

You have chosen a wrong input. Please try again
 Computer's value is 0. Your value is 1


matrix([[11,  0, 13],
        [21, 22,  0],
        [ 0, 32, 33]])

In [102]:
x = 0
y = 0
for i in range(3):
    #print (i)
    print (A[i,1])
    if A[i,1] == 1:
        x = x + 1
    if A[i,1] == 0:
        y = y + 1
print ("Following line is value for x and y")
print (x,y)
if x == 2 and y == 0:
    print ("If this is my turn, Computer is going to win")
    
if x == 3:
    print ("Computer wins")
if y == 3:
    print ("You Win")

1
22
32
Following line is value for x and y
1 0


In [81]:
if A[R,C] > 1:
    A[R,C] = 1
if A[R,C] < 2:
    print("This one is done. Chose another one")

This one is done. Chose another one


In [80]:
A

matrix([[11,  1, 13],
        [21, 22, 23],
        [31, 32, 33]])

In [84]:
sum(sum(A.T))

matrix([[25, 66, 96]])

In [85]:
A[:1]

matrix([[11,  1, 13]])

In [ ]:
A =  (np.matrix([[0,0,0],[0,0,0],[0,0,0]]))